version: '3.8'

services:
 backend:
   image: tarun309/hld-chat-backend:latest
   build:
     context: ./backend # Path to the backend Dockerfile
   ports:
     - "8081:8081"


 chat-backend-2:
   image: tarun309/hld-chat-backend2:latest
   build:
     context: ./backend # Path to the backend Dockerfile
   ports:
     - "8084:8081"


 auth-backend:
   image: tarun309/hld-chat-auth:latest
   build:
     context: ./auth # Path to the auth backend Dockerfile
   ports:
     - "8080:8080" 


 frontend:
   image: tarun309/hld-chat-client:latest
   build:
     context: ./client # Path to the frontend Dockerfile
   ports:
     - "3000:3000"
   depends_on:
     - backend # Wait for backend service to be ready before starting frontend


 frontend-secondary:
   image: tarun309/hld-chat-client2:latest
   build:
     context: ./client_2 # Path to the frontend Dockerfile
   ports:
     - "3001:3000"
   depends_on:
     - backend # Wait for backend service to be ready before starting frontend